export const ASSET_TYPES = [
  "cash Cash/Money Market",
  "bills Fixed Income: Bills (1 YR or Less)",
  "stb Fixed Income: Short Term Bonds (1 - 3 YRS)",
  "itb Fixed Income: Intermediate Term Bonds (3 - 15 YRS)",
  "ltb Fixed Income: Long Term Bonds (15 - 30 YRS)",
  "commodoties Real Assets: Commodoties",
  "gold Real Assets: Gold",
  "reits Real Assets: Real Estate Invesment Trusts (REITs)",
  "tsm Equities: Total Stock Market (TSM)",
  "dlcb Equities: Domestic Large Cap Blend (DLCB)",
  "dlcg Equities: Domestic Large Cap Growth (DLCG)",
  "dlcv Equities: Domestic Large Cap Value (DLCV)",
  "dmcb Equities: Domestic Medium Cap Blend (DMCB)",
  "dmcg Equities: Domestic Medium Cap Growth (DMCG)",
  "dmcv Equities: Domestic Medium Cap Value (DMCV)",
  "dscb Equities: Domestic Small Cap Blend (DSCB)",
  "dscg Equities: Domestic Small Cap Growth (DSCG)",
  "dscv Equities: Domestic Small Cap Value (DSCV)",
  "ilcb Equities: International Large Cap Blend (ILCB)",
  "ilcg Equities: International Large Cap Growth (ILCG)",
  "ilcv Equities: International Large Cap Value (ILCV)",
  "imcb Equities: International Medium Cap Blend (IMCB)",
  "imcg Equities: International Medium Cap Growth (IMCG)",
  "imcv Equities: International Medium Cap Value (IMCV)",
  "iscb Equities: International Small Cap Blend (ISCB)",
  "iscg Equities: International Small Cap Growth (ISCG)",
  "iscv Equities: International Small Cap Value (ISCV)",
];
